env:
  browser: true
  es6: true
extends:
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
overrides:
  - files:
    - '*.ts'
    - '*.tsx'
    extends:
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    - 'plugin:react/jsx-runtime'
    - 'standard-with-typescript'
    parserOptions:
      project: ['./tsconfig.json' ]
plugins:
  - react
rules: {}

settings:
  react:
    version: 'detect'