version: "3.9"
services:
  frontend:
    image: "${DOCKER_IMAGE}"
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}:/app"
      - "/app/node_modules"
    environment:
      CHOKIDAR_USEPOLLING: "true"